apiVersion: v1
kind: Secret
metadata:
  name: micropay-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: micropay_pass
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: micropay_pass
  JWT_SECRET: micropay_jwt_secret_key_123456
