spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER:-admin}:${CONFIG_SERVER_PASSWORD:-micropay_secure}@config-server:8888

server:
  port: ${SERVER_PORT:8084}