spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://${SPRING_SECURITY_USER_NAME:-admin}:${SPRING_SECURITY_USER_PASSWORD:-micropay_secure}@config-server:8888

server:
  port: ${SERVER_PORT:8084}